### ISSUE TITLE
fix(c/v3-engine): wrong node id when being a subgraph of apollo federation

### ISSUE THREAD

**Issue by praveenweb** [praveenweb/test-github-webhooks#18]
### Component

c/v3-engine

### What is the current behaviour?

node id is given like this.

```
eyJ2ZXJzaW9uIjoxLCJ0eXBlbmFtZSI6IkNoYXQiLCJpZCI6eyJ1aWQiOiJkODAzMWY1OC1kZWZlLTQzNDMtYjlkZS02MDI0OTRkMWQ5MzMifX0=
```

whose base64-decoded result is like this.

```
{"version":1,"typename":"Chat","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

### What is the expected behaviour?

The `typename` should be different.

```
{"version":1,"typename":"Thread","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

### How to reproduce the issue?

1. I configured DDN to support Relay.

```yaml
kind: Model
version: v1
definition:
  globalIdSource: true
---
kind: ObjectType
version: v1
definition:
  globalIdFields:
    - uid
```

2. I enabled Apollo Federation.

```yaml
kind: GraphqlConfig
version: v1
definition:
  apolloFederation:
    enableRootFields: true
---
kind: Model
definition:
  graphql:
    apolloFederation:
      entitySource: true
---
kind: ObjectType
version: v1
definition:
  graphql:
    apolloFederation:
      keys:
        - fields:
            - uid
```

3. Postgres has tables `thread` and `chat`, each of whose pk is `uid`.

4. I created another GraphQL server whose schema is like this. 

```graphql
scalar Uuid

extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.6", import: ["@key", "@shareable", "@authenticated", "@requiresScopes", "@policy"])

type Thread @key(fields: "uid") {
  uid: Uuid
}

type Chat @key(fields: "uid") {
  uid: Uuid
}

type Chunk {
  id: ID!
  chat: Chat!
  text: String!
  isLast: Boolean!
}

extend type Subscription {
  chunk: Chunk!
}
```

5. I federated DDN and the other GraphQL server by apollo federation. 
I use [Hive](https://the-guild.dev/graphql/hive) as a gateway. 
DDN is a subgraph of the apollo federation gateway. 

6. From client, I executed this.

```graphql
  subscription ChunkSubscription {
    chunk {
      chat {
        threadUid # `chat` table has a fk threadUid
        thread {
          id
        }
      }
    }
  }
```

7. If I see the result, it's wrong.

```js
console.log(chunk.chat.thread.id)
// eyJ2ZXJzaW9uIjoxLCJ0eXBlbmFtZSI6IkNoYXQiLCJpZCI6eyJ1aWQiOiJkODAzMWY1OC1kZWZlLTQzNDMtYjlkZS02MDI0OTRkMWQ5MzMifX0=
```

Base-64 decoded result of the `id` is like this.

```json
{"version":1,"typename":"Chat","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

`uid` (`d8031f58-defe-4343-b9de-602494d1d933`) is right data, but `typename` is wrong.
The `typename` should be `"Thread"`.

P.S. When I executed some(not exhaustive) other queries, it works.

For example, this query

```graphql
query MyQuery {
  threadByUid(uid: "d8031f58-defe-4343-b9de-602494d1d933"){ 
    id
  }
}
```

responds with a right id.

```json
{
  "data": {
    "threadByUid": {
      "id": "eyJ2ZXJzaW9uIjoxLCJ0eXBlbmFtZSI6IlRocmVhZCIsImlkIjp7InVpZCI6ImQ4MDMxZjU4LWRlZmUtNDM0My1iOWRlLTYwMjQ5NGQxZDkzMyJ9fQ=="
    }
  }
}
```

```jsonc
// decoded id
{"version":1,"typename":"Thread","id":{"uid":"d8031f58-defe-4343-b9de-602494d1d933"}}
```

### Keywords

apollo federation
entity
subgraph
node id
global id
relay
typename
